### ISSUE TITLE
image not booting with 5.10.x

### ISSUE THREAD

**Issue by pankajjoshi347** [sifive/meta-sifive#14]
copied image with the mentioned command but image is not booting further
SiFive FSBL:       2018-03-20
HiFive-U serial #: 00000127

after the above log i am not able to see anything on the console. what could be the reason kindly help??

i have made following changes in the freedom-u540.conf  file

**RISCV_SBI_FDT ?= "hifive-unleashed-a00.dtb"**
## Use this to add Microsemi Expansion board support
#RISCV_SBI_FDT ?=  "hifive-unleashed-a00-microsemi.dtb"

SERIAL_CONSOLES = "115200;ttySIF0"

MACHINE_EXTRA_RRECOMMENDS += " kernel-modules"

IMAGE_FSTYPES += "wic.xz ext4 tar.xz"
KERNEL_DEVICETREE ?= "sifive/${RISCV_SBI_FDT}"

## Do not update fstab file when using wic images
#WIC_CREATE_EXTRA_ARGS ?= "--no-fstab-update"

EXTRA_IMAGEDEPENDS += "u-boot"
UBOOT_MACHINE = "sifive_fu540_defconfig"

##  fails it will fall back to local images in the boot partition.
UBOOT_ENV ?= "mmc-boot"

# U-Boot SPL
SPL_BINARY ?= "spl/u-boot-spl.bin"

# U-Boot ITB (FIT image with U-Boot S-mode, OpenSBI FW_DYNAMIC, DTB [from
# U-Boot source code tree])
UBOOT_SUFFIX ?= "itb"

## wic default support
WKS_FILE_DEPENDS ?= " \
    opensbi \
    e2fsprogs-native \
    bmap-tools-native \
"

IMAGE_BOOT_FILES ?= " \
    Image.gz \
    **hifive-unleashed-a00.dtb \**
    boot.scr.uimg \
"

_Originally posted by @pankajjoshi347 in https://github.com/sifive/meta-sifive/issues/13#issuecomment-778078799_

**Comment by tprrt** [comment]
This issue is fixed.
