### ISSUE TITLE
What is CONFIG_SIFIVE_BEU ?

### ISSUE THREAD

**Issue by xnox** [sifive/meta-sifive#15]
```
$ git grep SIFIVE_BEU
recipes-kernel/linux/files/unmatched/defconfig:CONFIG_SIFIVE_BEU=y
```

Yet in no kernel trees or patches I see that. Is that just obsolete config option, or some driver is still not published?

**Comment by davidlt** [comment]
SiFive Bus Error Unit (BUS). Seems I forgot to remove it from the defconfig after some testing. The driver was posted for upstream review in November 2020. Some patches got approved, some not, but the whole series needs rebasing at this point. BEU patches are not incl. in the kernel patches within meta-sifive and they are not required for a proper operation of the board.
