### ISSUE TITLE
do_rootfs fail 

### ISSUE THREAD

**Issue by risonwung** [sifive/meta-sifive#18]
I want to build qemuriscv64 image using this original source code, but encounted this problem: meta-sifive ERROR: demo-coreip-cli-1.0-r0 do_rootfs: The postinstall intercept hook 'update_gtk_immodules_cache' failed, details in /home/rison/riscv-sifive/build/tmp-glibc/work/qemuriscv64-oe-linux/demo-coreip-cli/1.0-r0/temp/log.do_rootfs.
Any one knows how to solve this?

**Comment by risonwung** [comment]
I have solved this issue. There are two points need be changed. First point, add "mkdir -p $D${libdir}/gtk-3.0/3.0.0" into update_gtk_immodules_cache. Second, add "mkdir -p $D/packages" into update_mine_database.

**Comment by davidlt** [comment]
I have never seen this issue before. Could you send a patch for a review to the upstream?

**Comment by tprrt** [comment]
This issue is fixed.
