### ISSUE TITLE
Changing the model property in the devicetree is not a good idea

### ISSUE THREAD

**Issue by xypron** [sifive/meta-sifive#22]
The following patch changes the model property in the Unmatched devicetree:

https://github.com/sifive/meta-sifive/blob/909e6a67b0d1a6bc64adcb54848952c207c77cb0/recipes-kernel/linux/files/0006-riscv-sifive-unmatched-remove-A00-from-model.patch#L19

The model property is used by software like flash-kernel to identify boards. Hence this property should not be changed in upstream Linux. Please, drop the patch.

**Comment by tprrt** [comment]
Done
