### ISSUE TITLE
Typo in remote thermal limit patch

### ISSUE THREAD

**Issue by Cirromulus** [sifive/meta-sifive#24]
`TMP451_RETMOE_THERM_LIMIT_INIT_VALUE` should be `TMP451_REMOTE_THERM_LIMIT_INIT_VALUE`

https://github.com/sifive/meta-sifive/blob/8353752446a3b2c13f6a2fac259d8b7a09520a26/recipes-bsp/u-boot/files/unmatched/0012-board-sifive-spl-Set-remote-thermal-of-TMP451-to-85-.patch#L36

Nothing big, just to mention it :)

**Comment by davidlt** [comment]
CC @VincentZWC

**Comment by tprrt** [comment]
Should be fixed.
