### ISSUE TITLE
SD card partitions and copy U-Boot SPL, OpenSBI, U-Boot and rootFS image's to uSD card manually.

### ISSUE THREAD

**Issue by cghalibkhan** [sifive/meta-sifive#38]
Hello floks,

As per the Readme file once demo-coreip-cli-freedom-u540.wic.xz image is build and we are flashing image on SD-card with following command,
$ xzcat demo-coreip-cli-freedom-u540.wic.xz | sudo dd of=/dev/sdX bs=512K iflag=fullblock oflag=direct conv=fsync status=progress.

I have a few questions with wic.xz image like, 

1. How demo-coreip-cli-freedom-u540.wic.xz image creating partitions on SD-card?

- As per my knowledge to create partitions it's using freedom-u540-spl-opensbi.wks file but one thing i was not getting is, if i Run those .wks file commands i was not able to create partitions. 
- How partitions are created, if i want to create partitions manually how can do it?

2. How to copy the U-Boot SPL, OpenSBI, U-Boot and rootFS image's 

- on BOOT partition following files to uSD card manually.
boot.scr.uimg  extlinux/  hifive-unleashed-a00-microsemi.dtb  Image.gz

And boot u540 board successfully.

can anyone help me to do this?

Thanks in advance,
khan.

**Comment by jim-wilson** [comment]
You already have a bootable image after the xzcat and dd, so no need to do anything else.  Just boot it.

If you want to know how to build an image from scratch by hand, then I would suggest looking at
[https://github.com/carlosedp/riscv-bringup/tree/master/unmatched](https://github.com/carlosedp/riscv-bringup/tree/master/unmatched)
