### ISSUE TITLE
PWM LED need not be scoped in soc()

### ISSUE THREAD

**Issue by xnox** [sifive/meta-sifive#39]
In https://github.com/sifive/meta-sifive/blob/2022.01/recipes-kernel/linux/files/0005-SiFive-HiFive-Unleashed-Add-PWM-LEDs-D1-D2-D3-D4.patch

the PWM LED got scoped inside soc();

in mainline soc(); node got removed as it is redundant, and PWM LED can and should be declared outside of soc(); node, just like they are in unmatched.

**Comment by tprrt** [comment]
Done
