### ISSUE TITLE
2022.04  do_rootfs fail

### ISSUE THREAD

**Issue by NEU-Fly** [sifive/meta-sifive#46]
I want to build qemuriscv64 image using this original source code, but encounted this problem:
`ERROR: demo-coreip-cli-1.0-r0 do_rootfs: The postinstall intercept hook 'update_mime_database' failed, details in /data/htf/riscv-sifive/build/tmp-glibc/work/qemuriscv64-oe-linux/demo-coreip-cli/1.0-r0/temp/log.do_rootfs
ERROR: Logfile of failure stored in: /data/htf/riscv-sifive/build/tmp-glibc/work/qemuriscv64-oe-linux/demo-coreip-cli/1.0-r0/temp/log.do_rootfs.2028911
ERROR: Task (/data/htf/riscv-sifive/freedom-u-sdk/recipes-sifive/images/demo-coreip-cli.bb:do_rootfs) failed with exit code '1'` 
Any one knows how to solve this?

**Comment by tprrt** [comment]
This issue no longer occurs.

In additition, the demo-coreip-cli image has been moved to the [freedom-u-sdk](https://github.com/sifive/freedom-u-sdk/) layer.
