### ISSUE TITLE
Update to nss 3.50 breaks fresh build.

### ISSUE THREAD

**Issue by MarcKarasek** [sifive/meta-sifive#5]
Did a fresh clone and attempt qemu build per readme.md

Fails on no recipe available:
ERROR: No recipes available for:
  /media/marckarasek/source/riscv-sifive/meta-sifive/recipes-support/nss/nss_3.50.bbappend

**Comment by davidlt** [comment]
Could you try again? I just pushed manifest changes (which I forgot to do before).

**Comment by MarcKarasek** [comment]
Did a fresh clone and sync ...
Building ok now...

**Comment by MarcKarasek** [comment]
Fixed
