### ISSUE TITLE
testing qemuriscv32 support

### ISSUE THREAD

**Issue by jim-wilson** [sifive/meta-sifive#9]
I was curious if it was possible to build for qemuriscv32.  I used the demo-coreip-cli target with 2020.05.  I found a typo in the llvm sources, and two places with hooks for riscv64 that I had to duplicate for riscv32.  The next problem is that perf doesn't compile, complaining that SYS_futex is undefined.  I haven't tried to debug that yet.

[qemuriscv32-patch.txt](https://github.com/sifive/meta-sifive/files/4743898/qemuriscv32-patch.txt)

**Comment by tprrt** [comment]
This layer no longer provides support for Qemu RISC-V 32 bits.
